### ISSUE TITLE
Segment Fault

### ISSUE THREAD

**Issue by SpaceboyRoss01** [tinyalsa/tinyalsa#109] opened 2018-01-31 06:32 UTC
I've just added tinyalsa to my Linux distro (BlueSkyOS, Version 0.2.0-beta) and I tried to run tinypcminfo but I got a Segment Fault. I've run dmesg and I found out this:
```
[   47.171027] tinypcminfo[1072]: segfault at 1 ip 0000000000000001 sp 00007ffc65179ce8 error 14 in tinypcminfo[7fcd26e30000+6000]
```
I'm using musl for libc if that helps at all, and I have tested all the tinyalsa commands but they don't work.

**Comment by tay10r** [comment] 2018-01-31 13:15
Well it looks like there's a jump being made into 0x01 for some reason. Can you provide a download link to a disk image that I can test this on?

**Comment by SpaceboyRoss01** [comment] 2018-01-31 15:01
https://github.com/Ross-Software/BlueSkyOS/releases/download/v0.2.0-beta/x86-64.iso

**Comment by tay10r** [comment] 2018-01-31 15:48
Okay great. I'll take a look at it later today

**Comment by SpaceboyRoss01** [comment] 2018-01-31 15:48
The default password for root is blueskyos

**Comment by tay10r** [comment] 2018-01-31 15:50
okay, thanks.

**Comment by tay10r** [comment] 2018-01-31 22:52
As you may have found out, I was not able to start your operating system in QEMU. I'll need to do this so I can reproduce the issue. I'll revisit this when I can run your operating system.

**Comment by tay10r** [comment] 2018-01-31 23:33
I don't think this is a problem with tinyalsa.

It looks like all the programs you have in `/usr/bin` that aren't symbolic links will segfault when you try to run them. I looked at the symbol table and found a lot of glibc references. Are you sure you compiled these programs to utilize musl? I would also advise getting tools like valgrind, binutils, and strace into your system, at least in the development version. I had to mount the cdrom just so I could examine them and that only tells me so much. That is the only advice I can offer you.

I'm closing this issue. You can reopen it if you've found out something else that is specific to the tinyalsa programs.

**Closed by tay10r** 2018-01-31 23:33 UTC
