### ISSUE TITLE
How to capture playback sound use tinyalsa?

### ISSUE THREAD

**Issue by jerryyyq** [tinyalsa/tinyalsa#166] opened 2020-06-23 10:36 UTC
I want capture playback sound on ubuntu and android.
I call pcm_open() and pcm_readi() and I try:
mixer_get_ctl_by_name(mixer, "Loopback Mixing");
mixer_ctl_set_enum_by_string(ctl, "Enabled");

But, allways record wav from MIC, not from playing sound.
How to do I can?
Thank you very much.

-------------- My sound card Device Info: ------------------------
```
yangyuqi@yangyuqi-T450:~/sound$ tinymix -D 1 contents
Number of controls: 30
ctl	type	num	name                                    value
0	INT	2	Speaker Playback Volume                 0, 0 (range 0->87)
1	BOOL	2	Speaker Playback Switch                 Off, Off
2	INT	2	Headphone Playback Volume               87, 87 (range 0->87)
3	BOOL	2	Headphone Playback Switch               On, On
4	BOOL	2	Headphone Playback Switch               On, On
5	ENUM	1	Loopback Mixing                         Disabled, > Enabled, 
6	INT	2	Dock Mic Playback Volume                0, 0 (range 0->31)
7	BOOL	2	Dock Mic Playback Switch                Off, Off
8	INT	2	Mic Playback Volume                     0, 0 (range 0->31)
9	BOOL	2	Mic Playback Switch                     Off, Off
10	ENUM	1	Auto-Mute Mode                          Disabled, > Enabled, 
11	INT	2	Capture Volume                          37, 37 (range 0->63)
12	BOOL	2	Capture Switch                          On, On
13	INT	2	Dock Mic Boost Volume                   0, 0 (range 0->3)
14	INT	2	Mic Boost Volume                        0, 0 (range 0->3)
15	INT	2	Internal Mic Boost Volume               0, 0 (range 0->1)
16	INT	2	Beep Playback Volume                    0, 0 (range 0->31)
17	BOOL	2	Beep Playback Switch                    Off, Off
18	ENUM	1	Mic Mute-LED Mode                       On, Off, Follow Capture, > Follow Mute, 
19	INT	1	Master Playback Volume                  66 (range 0->87)
20	BOOL	1	Master Playback Switch                  On
21	BOOL	1	Dock Mic Jack                           Off
22	BOOL	1	Mic Jack                                Off
23	BOOL	1	Internal Mic Phantom Jack               On
24	BOOL	1	Speaker Phantom Jack                    On
25	BOOL	1	Dock Headphone Jack                     Off
26	BOOL	1	Headphone Jack                          On
27	INT	4	Playback Channel Map                    3, 4, 0, 0 (range 0->36)
28	INT	2	Capture Channel Map                     0, 0 (range 0->36)
29	INT	2	PCM Playback Volume                     255, 255 (range 0->255)
yangyuqi@yangyuqi-T450:~/sound$ 
```

**Comment by tay10r** [comment] 2020-06-24 11:55
Did you have a look at the PCM examples? A PCM is basically a mic input or a speaker output

**Comment by jerryyyq** [comment] 2020-06-26 09:10
Yes, I have looked these examples. but not find the right example.
I need function to implement read from speaker ( record from sound card, not from MIC. I want record placeback sound), do you understand？

**Comment by tay10r** [comment] 2020-06-26 13:00
I see what you mean now. Which operating system do you have?

**Comment by jerryyyq** [comment] 2020-06-28 02:21
please read my message carefully，My first sentence is : "I want capture playback sound on ubuntu and android."
My system is ubuntu 18.04 and android 9.0

**Comment by tay10r** [comment] 2020-06-28 03:00
@jerryyyq My apologies! I see. It's going to be different for both operating systems.

For Ubuntu, you'll need to use a loopback device. There's plenty of info on doing this from Google, so let me know if you have any issues with TinyALSA regarding that process.

For Android, you'll have to reference the SDK and figure out where you want to use it from there. I don't think the SDK exposes the TinyALSA API. You'd probably be using a separate layer of abstraction in Java.

Just to be clear, recording what's played through the speaker isn't something that TinyALSA supports directly.

**Comment by tay10r** [comment] 2020-07-07 03:50
I don't have an exact set of instructions I could give you to do it. This isn't really in the scope of the library.

**Comment by jerryyyq** [comment] 2020-07-08 10:53
I don't think so.
Because ALSA have somd pcm_hook functions, why tinyALSA not support?

**Comment by tay10r** [comment] 2020-07-08 15:01
Closing this because it's a duplicate of #167. Please don't open the same issue twice!

**Closed by tay10r** 2020-07-08 15:01 UTC
